### ISSUE TITLE
django-adminplus 0.2 compatibility with Django 1.4.5

### ISSUE THREAD

**Issue by lVlayhem** [jsocol/django-adminplus#11]
I have -e git://github.com/jsocol/django-adminplus#egg=django-adminplus in requirements.txt
I installed Django and django-adminplus in virtualenv and lost list of Custom Views in /admin/
Nevertheless I could view them directly:
```python
admin.site.register_view('django-ses', dashboard, _('Django SES Stats'))
```
and URL /admin/django-ses/ works fine.
After that I installed version 0.1.7 and configured urls.py (adminplus instead of adminplus.sites in imports):

    pip install -e git://github.com/jsocol/django-adminplus.git@09fa38724e8e05afc78f912da0ed78ef892da910#egg=django-adminplus

And got Custom Views list back.
Is it a bug?

**Comment by camilonova** [comment]
@jsocol seems is time to close this.

**Comment by jsocol** [comment]
@camilonova yep! thanks for the ping :+1:
