### ISSUE TITLE
The decorator admin.register not work anymore using AdminPlus

### ISSUE THREAD

**Issue by Nekmo** [jsocol/django-adminplus#27]
Tested usign Django 1.8. Classes registered with decorator are not shown anymore.

**Comment by dunkelstern** [comment]
Same in 1.7, Workaround:

Instead of `@admin.register(Model)` use `@admin.register(Model, site=admin.site)`

**Comment by Nekmo** [comment]
I do not care about my applications as both third-party applications. This module can not be used in Django 1.7+.

**Comment by jsocol** [comment]
v0.4 (out now) should fix this. Please open new issues if it doesn't!
