### ISSUE TITLE
Could you release a new version on pypi please?

### ISSUE THREAD

**Issue by mfa** [jsocol/django-adminplus#30]

**Comment by bashu** [comment]
Any chance to see 0.4 release soon?

**Comment by bashu** [comment]
everyone is dead?

**Comment by drdaeman** [comment]
Indeed, a new release on PyPI would be very nice thing to have. Listing dependency as `-e git+https...` isn't pretty.

@jsocol sorry to bother, but if you have time for this, would you please consider uploading a new release?

**Comment by jsocol** [comment]
> everyone is dead?

indeed.

OK, version [v0.4](https://pypi.python.org/pypi/django-adminplus/0.4) is out and tagged!
