### ISSUE TITLE
What to replace 

### ISSUE THREAD

**Issue by joeestes86** [jsocol/django-adminplus#31]
In the instructions it says:
To use AdminPlus in your Django project, you'll need to replace django.contrib.admin.site, which is an instance of django.contrib.admin.sites.AdminSite. I recommend doing this in urls.py right before calling admin.autodiscover():

Where is django.contrib.admin.site ?  It is not in the urls.py in the example below.  Also, what should it be replaced with?

**Comment by jsocol** [comment]
[Installing AdminPlus](https://github.com/jsocol/django-adminplus#installing-adminplus) in the README has example code for what the end result should look like. If you're using Django >= 1.7, make sure to note the change to `INSTALLED_APPS` at the bottom of the section.
