### ISSUE TITLE
Maintain a changelog?

### ISSUE THREAD

**Issue by olivierlefloch** [jsocol/django-adminplus#34]
Hi! We really enjoy `django-adminplus` features, but it would be great to have a summarized changelog between versions to more easily figure out what has changed.

For now I'll look at the changelog, but it's not completely obvious:

https://github.com/jsocol/django-adminplus/compare/v0.3...v0.4

**Comment by mlorant** [comment]
Totally agree. Even though it impacts only admins of a website, the lack of changelog can discourage upgrades...

**Comment by jsocol** [comment]
I'll try to do it going forward. If anyone wants to open a PR with a retroactive one, that'd be great. 



--
