### ISSUE TITLE
Django 1.9

### ISSUE THREAD

**Issue by ezegolub** [jsocol/django-adminplus#37]
Hi, i've been trying to use this module with Django 1.9, but overriding admin.site in urls.py causes the 'disappereance' of all the links in the index, my guess is that it's not registering the models and admins in admin.py
Any ideas? Any extra info i could provide? 

Thanks!

**Comment by jsocol** [comment]
Did you replace `django.contrib.admin` with `django.contrib.admin.apps.SimpleAdminConfig` in `INSTALLED_APPS`? (I realize the README is badly worded here, and implies that only needs to be done for 1.7, but it's really ≥1.7.)

**Comment by ezegolub** [comment]
That was the issue, thanks a lot! for the quick answer!!

**Comment by jsocol** [comment]
I updated the installation instructions to make it clearer. Thanks for pointing it out!
