### ISSUE TITLE
Passing arguments?

### ISSUE THREAD

**Issue by renegadeofunk** [jsocol/django-adminplus#39]
Hello,

Is there a way to pass arguments to custom admin views? I'm trying to make an "edit object" page that can access the object of a different tenant in a multi-tenant environment (using django-tenant-schemas). To do this I need to pass the item id and tenant to my edit page but I haven't been successful at this so far. Do I need to override the admin urls myself perhaps?

Thanks,
William

**Comment by jsocol** [comment]
adminplus is really intended to fill in the gap for admin views that are not connected to a specific object or model at all. There might be a use-case for better-supporting path arguments, but I don't think you need to do so here.

Using [ModelAdmin](https://docs.djangoproject.com/en/1.9/ref/contrib/admin/#modeladmin-methods) methods to control permissions, and overriding things like `save_model`, `get_model`, `has_*_permission`, etc, is probably the right way to go.

**Comment by renegadeofunk** [comment]
That's ok, I ended up just putting GET parameters in the links. Thanks anyway!
