### ISSUE TITLE
All registered views are wrapped in admin.site.admin_view.

### ISSUE THREAD

**Issue by chrisdew** [jsocol/django-adminplus#41]
In the README.md it says: "All registered views are wrapped in admin.site.admin_view".

What does this mean?

Am I wrong in assuming that this should wrap `my_view` in an `admin_view` such that when I render it with a template which  ```{% extends "admin/base_site.html" %}``` it should fill in the "Welcome, chris. View site / Change password / Log out" parts of the parent template?

It doesn't populate those parts, I just get an empty top-right header corner.

Have I misunderstood what "wrapped in admin.site.admin_view" means, or have I just written buggy code?

```
def my_view(request):
    return render(request, "admin/my_template.html")

admin.site.register_view('my_url', view=my_view)
```

If adminplus does not provide the `user` object for base.html to populate:
```
                {% if user.is_active and user.is_staff %}
                    {% url 'django-admindocs-docroot' as docsroot %}
                    {% if docsroot %}
                        <a href="{{ docsroot }}">{% trans 'Documentation' %}</a> /
                    {% endif %}
                {% endif %}
                {% if user.has_usable_password %}
```
then what is the cleanest way for me to do this?

**Comment by chrisdew** [comment]
P.S. Thanks for your earlier help, I have upgraded to Django 1.8.8.  (1.9.1 complained too much.)

**Comment by jsocol** [comment]
It's not very well documented by Django itself, but [AdminSite.admin_view](https://docs.djangoproject.com/en/1.8/ref/contrib/admin/#django.contrib.admin.ModelAdmin.get_urls) (about halfway through that section, or search for "admin_view" in the page, or the [docstring is better](https://github.com/django/django/blob/stable/1.8.x/django/contrib/admin/sites.py#L198-L220)) is a decorator that provides some default authorization checks and prevents caching. Most admin views should be wrapped in it.

AdminPlus doesn't, and can't, provide anything to the template context. You can pass in a dict of things to make available to the template as the [third argument to `render`](https://docs.djangoproject.com/en/1.9/topics/http/shortcuts/#render) or you can use [context processors](https://docs.djangoproject.com/en/1.8/ref/settings/#template-context-processors) to make things like the `request` object or the user available to all views.
