### ISSUE TITLE
Feature: Custom group names

### ISSUE THREAD

**Issue by stretch4x4** [jsocol/django-adminplus#44]
It would really help us if we could easily rename the Custom Views section as the pages we are putting in there don't really fit with that. Maybe a setting that is passed into the template?

It would also be really good if we could have multiple groups or even better add to existing application/model groups.

**Comment by stretch4x4** [comment]
When I have a little bit more time I might try to take a look at this to see how feasible some of these are.

**Comment by jsocol** [comment]
There are two issues here, renaming the section and groups.

I really don't care about renaming the section. But if someone wants to add it, I'd guess let's make it a property of the [`AdminPlusMixin`](https://github.com/jsocol/django-adminplus/blob/master/adminplus/sites.py#L11-L14) (e.g. `custom_list_title`) and stick that into [`extra_context`](https://github.com/jsocol/django-adminplus/blob/master/adminplus/sites.py#L71). And there'll need to be docs. It's just not a very high-value change, though.

Groups, I'm actively against supporting here. But there's something I think we could do to help make groups work, that's more of a general solution: adding the view object itself to [`custom_list`](https://github.com/jsocol/django-adminplus/blob/master/adminplus/sites.py#L63-L66), so each entry would look like `(path, name, view)`.

This would let people pass data into the template by attaching it to the view, like:

```python
def my_admin_view(request):
    return render(request, 'my_admin_template.html')
my_admin_view.group = 'group 1'
admin.site.register_view('my-admin-view', view=my_admin_view)
```

Then they can override the template to group however/wherever they want.

**Comment by stretch4x4** [comment]
Both of those suggestions seem like a good idea to me.
If I can find a couple of hours I will have a play, although not sure when I will get a chance to do that.

**Comment by jsocol** [comment]
Closing in favor of #50
