### ISSUE TITLE
Template different to main site

### ISSUE THREAD

**Issue by stretch4x4** [jsocol/django-adminplus#47]
We have noticed a few differences between the adminplus template and the standard django admin.

On all our custom views we loose our logout links, have tried to have a look in the templates but can't figure out what is causing them to disappear..

We also had to pass through our customised titles and headings, it would be excellent if the template picked up on the original values so each view didn't have to respecify them

**Comment by athre0z** [comment]
I'll assume you extend you templates from `admin/base_site.html`. When using those templates, make sure to include a correct context in your render call.

```python
@admin.site.register_view('meow')
def test_view(request):
    return render(
        request,
        'core/admin/blah.html',
        context=admin.site.each_context(request)
    )
```

See: [https://docs.djangoproject.com/en/1.9/ref/contrib/admin/#django.contrib.admin.AdminSite.each_context](https://docs.djangoproject.com/en/1.9/ref/contrib/admin/#django.contrib.admin.AdminSite.each_context)

**Comment by stretch4x4** [comment]
Cheers will take a look at that on Tuesday!

**Comment by jsocol** [comment]
@stretch4x4 did @athre0z's comment solve the issue?

**Comment by stretch4x4** [comment]
Sorry to not respond earlier, yes for memory I think it did, if not something very similar.

Cheers
________________________________

**Comment by jsocol** [comment]
OK, thanks! If anyone is still running into this, please reopen!
