### ISSUE TITLE
Completely broken on Django 1.9.5

### ISSUE THREAD

**Issue by peterfarrell** [jsocol/django-adminplus#48]
FYI, I followed the installation instructions including the information in #42 on Django 1.9.5 and either it's missing all the core modules, says I have no permissions to do anything in the admin despite being a superuser, or cannot find `admin.site.register_view` function at all when trying to register a custom function.

**Comment by pntmatheus** [comment]
Hi Peter, try put these lines in your url.py:
admin.site = AdminSitePlus()
admin.sites.site = admin.site
admin.autodiscover()
I have some troubles with the permissions too, I would like to conf some customs permissions, but i dont find a way in adminplus.

**Comment by peterfarrell** [comment]
@pntmatheus Thanks for the additional hint. I had tried that suggestion as well as it was outlined on:

https://github.com/jsocol/django-adminplus/issues/42#issuecomment-195555272

I couldn't get it to work with what you suggested either.

**Comment by pntmatheus** [comment]
If you can, share the source files...

**Comment by bradojevic** [comment]
Hi,
@pntmatheus solution worked for me on Django 1.9.5
However, if it help, I'm having exactly the same problem if I use AdminSite instead of AdminSitePlus

**Comment by pntmatheus** [comment]
Hi @bradojevic,

Seems your problem is foldrs' permissions.
Where are you run the app?

**Comment by jsocol** [comment]
Consolidating all of these into #42
