### ISSUE TITLE
Authentication and Authorization disappears in Django 1.9.6

### ISSUE THREAD

**Issue by mke21** [jsocol/django-adminplus#49]
Hi,

I resently upgraded from django 1.8.11 to 1.9.6. But now my "Authentication and Authorization" module in admin has disappeard. uncommenting the "admin.site = AdminSitePlus()" in my url lets it reappear again. Also downgrading to django 1.8.11 makes it appear again.
So I guess it is due to this app in combination with django 1.9.6. No idea what happens, though.

**Comment by jsocol** [comment]
Consolidating all of these in to #42
