### ISSUE TITLE
Now have to set admin.sites.site

### ISSUE THREAD

**Issue by AstraLuma** [jsocol/django-adminplus#52]
In order for default `@admin.register` to work, you have to also set `admin.sites.site` like so:

```
admin.site = admin.sites.site = AdminSitePlus()
```

**Comment by gitfred** [comment]
@astronouth7303 thanks!

**Comment by jordanambra** [comment]
Thanks for this report. Doing this also helped me get the other apps in INSTALLED_APPS like django.contrib.auth to show up.

**Comment by fesouza** [comment]
You saved the day!

**Comment by jsocol** [comment]
I'm going to close this out because I think with the App Config work in 2.x/3.x/4.x there are now better ways to install AdminPlus, but it will take me a little bit to catch up on it
