### ISSUE TITLE
How to hide the custom view from admin main page

### ISSUE THREAD

**Issue by gr8Adakron** [jsocol/django-adminplus#56]
As my custom view is linked with the urls inside one of the model views so, it requires variable to process the view. And when I am clicking on the custom view of the front page, its giving error as that link doesnt have required variable to process the view.
![screenshot from 2017-11-20 14-38-22](https://user-images.githubusercontent.com/16715364/33010483-aaac4c9a-ce00-11e7-886b-26547a95656a.png)

So, is there a way to hide the custom view **"TaxanomyTree"** ??

Thanks! in advance.

**Comment by jsocol** [comment]
Yes! If you add `visible=False` to the `register_view()` call, it won't show up in the list. That's documented in the README.
