### ISSUE TITLE
Django 4 support

### ISSUE THREAD

**Issue by ivorbosloper** [jsocol/django-adminplus#64]
Django 4 breaks with Exception:

 ```
 File "adminplus/sites.py", line 47, in get_urls
    from django.conf.urls import url
ImportError: cannot import name 'url' from 'django.conf.urls' (django/conf/urls/__init__.py)
```

The cause is; `django.conf.urls.url()` was deprecated since Django 3.1, [is removed in Django 4.0+](https://docs.djangoproject.com/en/4.0/releases/4.0/#features-removed-in-4-0). It can be resolved by using `path` or `re_path` , see [docs](https://docs.djangoproject.com/en/4.0/ref/urls/).

**Comment by cchacholiades** [comment]
Any plans on releasing this?

**Comment by joshua-jandyco** [comment]
@cchacholiades I don't know why I keep running into this situation. I'm building my first for production Django website and keep seeing projects like this recommended only to find they haven't been touched in years and don't do anything with pull requests that fix support for the latest Django.  

@jsocol Anything we can do to help get this merged?

**Comment by ivorbosloper** [comment]
Fixed with merge...

**Comment by helissonomc** [comment]
> It’s merged in a fork, not in this repo

where is this merged? i am trying to use the .5 version and it is not there

**Comment by jsocol** [comment]
I'm working on getting a new release cut. I believe this will be the last 0.x release

**Comment by helissonomc** [comment]
> I'm working on getting a new release cut. I believe this will be the last 0.x release

Nice! Thank you!

**Comment by jsocol** [comment]
It's out! https://pypi.org/project/django-adminplus/0.6/

Please file issues if you encounter anything with various versions of Django. I fully expect there to be issues given there hasn't been a release in ~8 years 😅
