### ISSUE TITLE
AdminPlus does not autodiscover 'sites' framework

### ISSUE THREAD

**Issue by gregsadetsky** [jsocol/django-adminplus#9]
Hi,

Congrats on AdminPlus! It's a great and very useful package.

I followed the Installing & Using instructions and have been able to add a custom view. However, when using AdminPlus, I noticed that some built-in models disappeared from the admin site; namely, the "sites" framework (... models related to the django-registration package also disappeared).

I was able to get the Sites admin back by doing

```
from django.contrib.sites.models import Site

admin.site = AdminSitePlus()
admin.site.register(Site)
```

It might be interesting to see if AdminPlus' autodiscovery could find out about the Sites framework, or note this in the documentation.

Cheers

**Comment by hellysmile** [comment]
I have same issue.

`sites` is registred by 

https://github.com/django/django/blob/master/django/contrib/admin/decorators.py#L14

``django.contrib.admin.sites import site`

which not is monkey patched on `admin.site = AdminSitePlus()`

my solution is 

```python

admin.site = AdminSitePlus()
admin.sites.site = admin.site
admin.autodiscover()
```

**Comment by jsocol** [comment]
Victor, this sounds like a different problem, and given how many major versions have come out, would you mind opening a new issue describing the symptoms you're seeing?



--
